name: pi_metro_2025_2
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  mongo_dart: ^0.10.5
  http: ^1.5.0
  flutter_secure_storage: ^9.2.4

  # Para gerar PDF
  path_provider: ^2.1.0
  pdf: ^3.10.8
  printing: ^5.13.0
  shared_preferences: ^2.5.3

  # Para gerar EXCEL
  
  excel: ^4.0.2          
  file_saver: ^0.3.1    
  open_filex: ^4.4.0     
  uuid: ^4.5.2

  # Image picker
  image_picker: any

  flutter_map: ^7.0.0
  latlong2: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.9.0
  json_serializable: ^6.11.1
  mockito: ^5.4.4
  gherkin: ^2.0.8
  flutter_gherkin: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/LogoMetro.png
